// SPOTIFY
export const SPOTIFY_INIT = 'SPOTIFY_INIT'
export const SPOTIFY_CONNECTION = 'SPOTIFY_CONNECTION'
export const SPOTIFY_USER_INFOS = 'SPOTIFY_USER_INFOS'

// MOODMUSIC
export const MOODMUSIC_TOP_ARTISTS = 'MOODMUSIC_TOP_ARTISTS'
export const LOGOUT = 'LOGOUT'